version: '2'
services: 
  nginx:
    image: nginx:stable
    ports: 
      - "8080:80"
    depends_on: 
      - php
    volumes_from: 
      - php
    volumes: 
      - ./images/nginx/config:/etc/nginx/conf.d
  php:
    image: php:7.3-fpm
    volumes: 
      - ./app:/mnt/app
  db:
    image: mysql:5
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    volumes: 
      - db:/var/lib/mysql
volumes: 
  db:
    driver: local