version: '2'
services: 
  db:
    image: mysql:5
    environment: 
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'app'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
    volumes: 
      - db:/var/lib/mysql
volumes: 
  db:
    driver: local